import { describe, it } from "node:test";
import { expectAll } from "./test-helpers.ts";

describe("docker", () => {
	it("allows normal local workflows", () =>
		expectAll("allow", [
			"docker ps -a",
			"docker images",
			"docker logs -f api",
			"docker inspect api",
			"docker build -t api:dev .",
			"docker build --platform linux/amd64 -t api:dev -f Dockerfile.prod .",
			"docker pull postgres:16",
			"docker run --rm -it -v $PWD:/app -w /app node:24 npm test",
			"docker run -d -p 5432:5432 --name pg -e POSTGRES_PASSWORD=x postgres:16",
			"docker run --rm --network host alpine wget -qO- localhost:8080",
			"docker start pg",
			"docker stop pg",
			"docker restart pg",
			"docker compose up -d",
			"docker compose up --build",
			"docker compose down",
			"docker compose ps",
			"docker compose logs -f api",
			"docker compose build",
			"docker compose pull",
			"docker-compose up -d",
			"docker-compose down",
			"docker --context orbstack ps",
			"docker version",
			"docker -v",
			"docker system df",
			"docker tag api:dev api:latest",
			"docker buildx build -t api .",
		]));

	it("asks for removal, pruning, host escape, registry and remote mutations", () =>
		expectAll("ask", [
			"docker rm -f pg",
			"docker rmi api:dev",
			"docker image rm api:dev",
			"docker image prune -a",
			"docker container prune",
			"docker volume rm pgdata",
			"docker volume prune",
			"docker network rm net",
			"docker system prune -af --volumes",
			"docker builder prune",
			"docker buildx prune",
			"docker compose rm -f",
			"docker compose down -v",
			"docker compose down --volumes",
			"docker compose down --rmi all",
			"docker compose up --remove-orphans",
			"docker-compose down -v",
			"docker exec -it api sh",
			"docker compose exec api sh",
			"docker compose run api sh",
			"docker run --privileged alpine",
			"docker run --pid=host alpine",
			"docker run --cap-add SYS_ADMIN alpine",
			"docker run --device /dev/kvm alpine",
			"docker run -v /var/run/docker.sock:/var/run/docker.sock alpine",
			"docker run -v /:/host alpine",
			"docker run --mount type=bind,source=/,target=/host alpine",
			"docker push registry/api:dev",
			"docker compose push",
			"docker login ghcr.io",
			"docker logout",
			"docker swarm init",
			"docker service create nginx",
			"docker context create remote --docker host=ssh://x",
			"docker context use remote",
			"docker --context remote compose up -d",
			"docker -H ssh://prod ps && docker -H ssh://prod restart api",
			"DOCKER_HOST=ssh://prod docker compose up -d",
		]));
});
