import { describe, it } from "node:test";
import { expectAll } from "./test-helpers.ts";

describe("kubectl", () => {
	it("allows reads", () =>
		expectAll("allow", [
			"kubectl get pods -A",
			"kubectl get pods -n kube-system -o wide",
			"kubectl get deploy api -o yaml",
			"kubectl get pods --context acme-product-prod",
			"kubectl describe pod api-123 -n app",
			"kubectl logs -f deploy/api -n app --tail=100",
			"kubectl logs api-123 -c sidecar --since=1h",
			"kubectl top pods -A",
			"kubectl top nodes",
			"kubectl explain deployment.spec",
			"kubectl api-resources",
			"kubectl version",
			"kubectl cluster-info",
			"kubectl diff -f manifest.yaml",
			"kubectl wait --for=condition=ready pod/api -n app",
			"kubectl port-forward svc/api 8080:80 -n app",
			"kubectl port-forward svc/api 8080:80 -n app > /dev/null 2>&1 &",
			"kubectl events -n app",
			"kubectl auth can-i list pods -A",
			"kubectl auth whoami",
			"kubectl rollout status deploy/api -n app",
			"kubectl rollout history deploy/api",
			"kubectl config get-contexts",
			"kubectl config current-context",
			"kubectl config use-context acme-product-staging",
			"kubectl config view",
			"kubectl apply -f m.yaml --dry-run=server",
			"kubectl apply -f m.yaml --dry-run=client -o yaml",
			"kubectl delete pod x --dry-run=client",
			"kubectl kustomize overlays/prod",
			"kubectl get pods | grep Running | wc -l",
			"kubectl get pods -A | grep -v Running",
			"kubectx acme-product-prod",
			"kubens app",
		]));

	it("asks for secret reads and unknown verbs", () =>
		expectAll("ask", [
			"kubectl get secret",
			"kubectl get secrets -A",
			"kubectl get secret db-creds -o yaml -n app",
			"kubectl get secret/db-creds",
			"kubectl describe secret db-creds",
			"kubectl get secrets.v1 -n app",
			"kubectl -n app get secret x",
			"kubectl get --raw /api/v1/nodes",
			"kubectl config view --raw",
			"kubectl neat get pods",
			"kubectl krew install ctx",
		]));

	it("denies writes", () =>
		expectAll("deny", [
			"kubectl apply -f m.yaml",
			"kubectl apply -k overlays/prod",
			"kubectl create deployment x --image=y",
			"kubectl create -f m.yaml",
			"kubectl delete pod x -n app",
			"kubectl delete -f m.yaml",
			"kubectl delete pod x --dry-run=none",
			"kubectl edit deploy api",
			"kubectl patch deploy api -p '{}'",
			"kubectl replace -f m.yaml",
			"kubectl scale deploy api --replicas=3",
			"kubectl label pod x a=b",
			"kubectl annotate pod x a=b",
			"kubectl set image deploy/api api=img:2",
			"kubectl expose deploy api --port=80",
			"kubectl autoscale deploy api --max=5",
			"kubectl rollout restart deploy/api -n app",
			"kubectl rollout undo deploy/api",
			"kubectl exec -it api-123 -- sh",
			"kubectl exec api-123 -- cat /etc/passwd",
			"kubectl attach api-123",
			"kubectl cp api-123:/tmp/x ./x",
			"kubectl debug node/n -it --image=busybox",
			"kubectl run tmp --image=busybox -it -- sh",
			"kubectl proxy",
			"kubectl drain node-1",
			"kubectl cordon node-1",
			"kubectl taint nodes n key=v:NoSchedule",
			"kubectl auth reconcile -f rbac.yaml",
			"kubectl config set-context x --namespace=y",
			"kubectl config delete-context x",
			"kubectl get pods --kubeconfig ~/.kube/config",
			"KUBECONFIG=~/.kube/config kubectl get pods",
			"kubectl get pods --as=system:admin",
			"kubectl get pods --token=abc --server=https://x",
			"kubectl get pods -A | xargs kubectl delete pod",
			"kubectl get pods -o name | xargs -I{} kubectl delete {}",
			"bash -c 'kubectl delete ns app'",
		]));
});
